INSERT INTO customer
  VALUES (101,'Ludwig','Pauli','All Sports Supplies','213 Erstwild Court',
          NULL,'Sunnyvale','CA','94086','408-789-8075');
INSERT INTO customer
  VALUES (102,'Carole','Sadler','Sports Spots','785 Geary St',
          NULL,'San Francisco','CA','94117','415-822-1289');
INSERT INTO customer
  VALUES (103,'Phillip','Currie','Phil''s Sports','654 Poplar',
          'P.O. Box 3498','Palo Alto','CA','94303','415-328-4543');
INSERT INTO customer
  VALUES (104,'Anthony','Higgins','Play Ball!','East Shopping Cntr.',
          '422 Bay Road','Redwood City','CA','94026','415-368-1100');
INSERT INTO customer
  VALUES (105,'Raymond','Vector','Los Altos Sports','1899 Le Loma Drive',
          NULL,'Los Altos','CA','94022','415-776-3249');
INSERT INTO customer
  VALUES (106,'George','Watson','Watson and Son','1143 Carver Place',
          NULL,'Mountain View','CA','94063','415-389-8789');
INSERT INTO customer
  VALUES (107,'Charles','Ream','Athletic Supplies','41 Jordan Avenue',
          NULL,'Palo Alto','CA','94304','415-356-9876');
INSERT INTO customer
  VALUES (108,'Donald','Quinn','Quinn''s Sports','587 Alvarado',
          NULL,'Redwood City','CA','94063','415-544-8729');
INSERT INTO customer
  VALUES (109,'Jane','Miller','Sport Stuff','Mayfair Mart',
          '7345 Ross Blvd.','Sunnyvale','CA','94086','408-723-8789');
INSERT INTO customer
  VALUES (110,'Roy','Jaeger','AA athletics','520 Topaz Way',
          NULL,'Redwood City','CA','94062','415-743-3611');
INSERT INTO customer
  VALUES (111,'Frances','Keyes','Sports Center','3199 Sterling Court',
          NULL,'Sunnyvale','CA','94085','408-277-7245');
INSERT INTO customer
  VALUES (112,'Margaret','Lawson','Runners and Others','234 Wyandotte Way',
          NULL,'Los Altos Hills','CA','94022','415-887-7235');
INSERT INTO customer
  VALUES (113,'Lana','Beatty','Sportstown','654 Oak Grove',
          NULL,'Menlo Park','CA','94025','415-356-9982');
INSERT INTO customer
  VALUES (114,'Frank','Albertson','Sporting Place','947 Waverly Place',
          NULL,'Redwood City','CA','94062','415-886-6677');
INSERT INTO customer
  VALUES (115,'Alfred','Grant','Gold Medal Sports','776 Gary Avenue',
          NULL,'Menlo Park','CA','94025','415-356-1123');
INSERT INTO customer
  VALUES (116,'Jean','Parmelee','Olympic City','1104 Spinosa Drive',
          NULL,'Mountain View','CA','94040','415-534-8822');
INSERT INTO customer
  VALUES (117,'Arnold','Sipes','Kids Korner','850 Lytton Court',
          NULL,'Redwood City','CA','94063','415-245-4578');
INSERT INTO customer
  VALUES (118,'Dick','Baxter','Blue Ribbon Sports','5427 College',
          NULL,'Oakland','CA','94609','415-655-0011');          
