INSERT INTO stock
  VALUES (1,'HRO','baseball gloves',250.00,'case','10 gloves/case');
INSERT INTO stock
  VALUES (1,'HSK','baseball gloves',800.00,'case','10 gloves/case');
INSERT INTO stock
  VALUES (1,'SMT','baseball gloves',450.00,'case','10 gloves/case');
INSERT INTO stock
  VALUES (2,'HRO','baseball',126.00,'case','24/case');
INSERT INTO stock
  VALUES (3,'HSK','baseball bat',240.00,'case','12/case');
INSERT INTO stock
  VALUES (4,'HSK','football',960.00,'case','24/case');
INSERT INTO stock
  VALUES (4,'HRO','football',480.00,'case','24/case');
INSERT INTO stock
  VALUES (5,'NRG','tennis racquet',28.00,'each','each');
INSERT INTO stock
  VALUES (5,'SMT','tennis racquet',25.00,'each','each');
INSERT INTO stock
  VALUES (5,'ANZ','tennis racquet',19.80,'each','each');
INSERT INTO stock
  VALUES (6,'SMT','tennis ball',36.00,'case','24 cans/case');
INSERT INTO stock
  VALUES (6,'ANZ','tennis balls',48.00,'case','24 cans/case');
INSERT INTO stock
  VALUES (7,'HRO','basketball',600.00,'case','24/case');
INSERT INTO stock
  VALUES (8,'ANZ','volleyball',840.00,'case','24/case');
INSERT INTO stock
  VALUES (9,'ANZ','volleyball net',20.00,'each','each');

